import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { basename, delimiter, join, resolve } from "node:path";
import { formatSkillsForPrompt, type ExtensionAPI, type ExtensionContext } from "@earendil-works/pi-coding-agent";
import { completeSimple, type AssistantMessage } from "@earendil-works/pi-ai";

type SkillSource = "project" | "agent-home" | "claude-home" | "custom";

interface Skill {
  name: string;
  description: string;
  location: string;
  source: SkillSource;
}

interface SkillRoot {
  path: string;
  source: SkillSource;
}

interface SkillSelection {
  version: 1;
  updatedAt: string;
  autoGenerated: boolean;
  selectionMethod?: "llm" | "heuristic" | "manual";
  enabledSkillLocations: string[];
}

interface ProjectSignals {
  isWebProject: boolean;
  hasBrowserUi: boolean;
  hasServerSurface: boolean;
  hasBlogContent: boolean;
}

const SKILL_DIR = "skills";
const CLAUDE_DIR = ".claude";
const AGENTS_DIR = ".agents";
const SKILL_FILE = "SKILL.md";
const CUSTOM_SKILL_PATHS_ENV = "PI_SKILL_PATHS";
const PI_DIR = ".pi";
const SELECTION_FILE = "skills-selection.json";
const MAX_CONTEXT_FILE_CHARS = 8_000;
const MAX_LS_ENTRIES = 120;
const ORANGE_ANSI = "\u001b[38;5;208m";
const RESET_ANSI = "\u001b[0m";

const WEB_UI_PACKAGES = [
  "@astrojs/react",
  "@sveltejs/kit",
  "@vitejs/plugin-react",
  "astro",
  "next",
  "nuxt",
  "react",
  "svelte",
  "vite",
  "vue",
];

const SERVER_PACKAGES = [
  "@nestjs/core",
  "@trpc/server",
  "apollo-server",
  "django",
  "express",
  "fastapi",
  "fastify",
  "flask",
  "hapi",
  "koa",
  "next",
  "rails",
];

function parseFrontmatter(markdown: string): Record<string, string> {
  if (!markdown.startsWith("---\n")) return {};

  const end = markdown.indexOf("\n---", 4);
  if (end === -1) return {};

  const frontmatter = markdown.slice(4, end);
  const values: Record<string, string> = {};

  for (const line of frontmatter.split("\n")) {
    const separator = line.indexOf(":");
    if (separator === -1) continue;

    const key = line.slice(0, separator).trim();
    const value = line.slice(separator + 1).trim().replace(/^[\'\"]|[\'\"]$/g, "");
    if (key) values[key] = value;
  }

  return values;
}

function readJsonFile(path: string): unknown {
  try {
    return JSON.parse(readFileSync(path, "utf-8"));
  } catch {
    return undefined;
  }
}

function readSkill(path: string, source: SkillSource, fallbackName: string): Skill | undefined {
  let markdown: string;
  try {
    markdown = readFileSync(path, "utf-8");
  } catch {
    return undefined;
  }

  const metadata = parseFrontmatter(markdown);
  const name = metadata.name?.trim() || fallbackName;
  if (!name) return undefined;

  return {
    name,
    description: metadata.description?.trim() || "",
    location: path,
    source,
  };
}

function discoverSkillRoot(root: SkillRoot): Skill[] {
  if (!existsSync(root.path)) return [];

  const directSkill = join(root.path, SKILL_FILE);
  if (existsSync(directSkill)) {
    const skill = readSkill(directSkill, root.source, basename(root.path));
    return skill ? [skill] : [];
  }

  let entries: string[];
  try {
    entries = readdirSync(root.path);
  } catch {
    return [];
  }

  const skills: Skill[] = [];
  for (const entry of entries) {
    const entryPath = join(root.path, entry);

    let stats;
    try {
      stats = statSync(entryPath);
    } catch {
      continue;
    }

    if (stats.isDirectory()) {
      const skill = readSkill(join(entryPath, SKILL_FILE), root.source, entry);
      if (skill) skills.push(skill);
      continue;
    }

    if (stats.isFile() && entry.endsWith(".md")) {
      const skill = readSkill(entryPath, root.source, entry.replace(/\.md$/, ""));
      if (skill) skills.push(skill);
    }
  }

  return skills;
}

function customSkillRoots(): SkillRoot[] {
  const rawPaths = process.env[CUSTOM_SKILL_PATHS_ENV];
  if (!rawPaths) return [];

  return rawPaths
    .split(delimiter)
    .map((path) => path.trim())
    .filter(Boolean)
    .map((path) => ({ path: resolve(path), source: "custom" as const }));
}

function skillIdentity(skill: Skill): string {
  return `${skill.name.toLowerCase()}\u0000${skill.description.toLowerCase()}`;
}

function discoverSkills(cwd: string): Skill[] {
  const home = homedir();
  const roots: SkillRoot[] = [
    { path: join(cwd, CLAUDE_DIR, SKILL_DIR), source: "project" },
    { path: join(home, AGENTS_DIR, SKILL_DIR), source: "agent-home" },
    { path: join(home, CLAUDE_DIR, SKILL_DIR), source: "claude-home" },
    ...customSkillRoots(),
  ];

  const seenLocations = new Set<string>();
  const seenIdentities = new Set<string>();
  const skills: Skill[] = [];

  for (const root of roots) {
    for (const skill of discoverSkillRoot(root)) {
      const identity = skillIdentity(skill);
      if (seenLocations.has(skill.location) || seenIdentities.has(identity)) continue;
      seenLocations.add(skill.location);
      seenIdentities.add(identity);
      skills.push(skill);
    }
  }

  return skills.sort((a, b) => a.name.localeCompare(b.name));
}

function packageNames(cwd: string): Set<string> {
  const packageJson = readJsonFile(join(cwd, "package.json"));
  if (!packageJson || typeof packageJson !== "object") return new Set();

  const names = new Set<string>();
  for (const key of ["dependencies", "devDependencies", "peerDependencies", "optionalDependencies"] as const) {
    const dependencies = (packageJson as Record<string, unknown>)[key];
    if (!dependencies || typeof dependencies !== "object") continue;
    for (const name of Object.keys(dependencies)) names.add(name.toLowerCase());
  }

  return names;
}

function fileExists(cwd: string, relativePath: string): boolean {
  return existsSync(join(cwd, relativePath));
}

function detectProjectSignals(cwd: string): ProjectSignals {
  const packages = packageNames(cwd);
  const hasPackage = (names: string[]) => names.some((name) => packages.has(name));
  const hasBrowserUi =
    hasPackage(WEB_UI_PACKAGES) ||
    fileExists(cwd, "index.html") ||
    fileExists(cwd, "src/App.tsx") ||
    fileExists(cwd, "src/App.jsx") ||
    fileExists(cwd, "app/page.tsx") ||
    fileExists(cwd, "pages/index.tsx");
  const hasServerSurface =
    hasPackage(SERVER_PACKAGES) ||
    fileExists(cwd, "api") ||
    fileExists(cwd, "server") ||
    fileExists(cwd, "app/api") ||
    fileExists(cwd, "src/server.ts") ||
    fileExists(cwd, "main.py") ||
    fileExists(cwd, "manage.py");
  const hasBlogContent =
    fileExists(cwd, "content/blog") ||
    fileExists(cwd, "blog") ||
    fileExists(cwd, "posts") ||
    fileExists(cwd, "src/content/blog");

  return {
    isWebProject: hasBrowserUi || hasServerSurface,
    hasBrowserUi,
    hasServerSurface,
    hasBlogContent,
  };
}

function shouldAutoEnableSkill(skill: Skill, signals: ProjectSignals): boolean {
  const name = skill.name.toLowerCase();

  if (skill.source === "project") return true;
  if (name === "blog-post") return signals.hasBlogContent;
  if (name === "browser-tools") return signals.hasBrowserUi;
  if (name === "optimize-design") return signals.hasBrowserUi;
  if (name === "optimize-website") return signals.isWebProject;
  if (name === "security-audit") return signals.hasServerSurface || signals.isWebProject;

  return false;
}

function createAutoSelection(cwd: string, skills: Skill[]): SkillSelection {
  const signals = detectProjectSignals(cwd);
  return {
    version: 1,
    updatedAt: new Date().toISOString(),
    autoGenerated: true,
    selectionMethod: "heuristic",
    enabledSkillLocations: skills
      .filter((skill) => shouldAutoEnableSkill(skill, signals))
      .map((skill) => skill.location),
  };
}

function isSelection(value: unknown): value is SkillSelection {
  if (!value || typeof value !== "object") return false;
  const selection = value as Record<string, unknown>;
  return selection.version === 1 && Array.isArray(selection.enabledSkillLocations);
}

function selectionPath(cwd: string): string {
  return join(cwd, PI_DIR, SELECTION_FILE);
}

function saveSelection(path: string, selection: SkillSelection): void {
  mkdirSync(resolve(path, ".."), { recursive: true });
  writeFileSync(path, JSON.stringify(selection, null, 2) + "\n", "utf-8");
}

function loadSelection(cwd: string): SkillSelection | undefined {
  const parsed = readJsonFile(selectionPath(cwd));
  return isSelection(parsed) ? parsed : undefined;
}

function selectedSkills(skills: Skill[], selection: SkillSelection): Skill[] {
  const enabledLocations = new Set(selection.enabledSkillLocations);
  return skills.filter((skill) => enabledLocations.has(skill.location));
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function readContextFile(cwd: string, relativePath: string): string | undefined {
  const path = join(cwd, relativePath);
  if (!existsSync(path)) return undefined;

  try {
    return readFileSync(path, "utf-8").slice(0, MAX_CONTEXT_FILE_CHARS);
  } catch {
    return undefined;
  }
}

function topLevelLs(cwd: string): string {
  try {
    return readdirSync(cwd)
      .filter((entry) => entry !== ".git" && entry !== "node_modules")
      .slice(0, MAX_LS_ENTRIES)
      .join("\n");
  } catch {
    return "";
  }
}

function renderProjectContext(cwd: string): string {
  const files = ["README.md", "README", "package.json", "pyproject.toml"];
  const parts = [`## ls\n${topLevelLs(cwd)}`];

  for (const file of files) {
    const content = readContextFile(cwd, file);
    if (content) parts.push(`## ${file}\n${content}`);
  }

  return parts.join("\n\n");
}

function renderSkillSelectionPrompt(cwd: string, skills: Skill[]): string {
  const skillList = skills
    .map((skill) => `- location: ${skill.location}\n  name: ${skill.name}\n  source: ${skill.source}\n  description: ${skill.description}`)
    .join("\n");

  return `Select only skills that are clearly relevant to this project. Prefer a small set. Include project-local skills unless obviously irrelevant. Return only JSON matching this shape: {"enabledSkillLocations":["absolute skill location", ...]}\n\n# Project context\n${renderProjectContext(cwd)}\n\n# Available skills\n${skillList}`;
}

function textFromAssistantMessage(message: AssistantMessage): string {
  return message.content
    .filter((content) => content.type === "text")
    .map((content) => content.text)
    .join("\n");
}

function parseJsonObject(text: string): unknown {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1];
  const raw = fenced ?? text;
  const start = raw.indexOf("{");
  const end = raw.lastIndexOf("}");
  if (start === -1 || end === -1 || end <= start) return undefined;

  try {
    return JSON.parse(raw.slice(start, end + 1));
  } catch {
    return undefined;
  }
}

function selectionFromModelResponse(text: string, skills: Skill[]): SkillSelection | undefined {
  const parsed = parseJsonObject(text);
  if (!parsed || typeof parsed !== "object") return undefined;

  const locations = (parsed as Record<string, unknown>).enabledSkillLocations;
  if (!Array.isArray(locations)) return undefined;

  const validLocations = new Set(skills.map((skill) => skill.location));
  return {
    version: 1,
    updatedAt: new Date().toISOString(),
    autoGenerated: true,
    selectionMethod: "llm",
    enabledSkillLocations: locations.filter((location): location is string => typeof location === "string" && validLocations.has(location)),
  };
}

async function createLlmSelection(cwd: string, skills: Skill[], ctx: ExtensionContext): Promise<SkillSelection | undefined> {
  if (!ctx.model) return undefined;

  const auth = await ctx.modelRegistry.getApiKeyAndHeaders(ctx.model);
  if (!auth.ok) return undefined;

  const message = await completeSimple(
    ctx.model,
    {
      systemPrompt: "You select relevant Pi agent skills for a software project. Be conservative to save context.",
      messages: [{ role: "user", content: renderSkillSelectionPrompt(cwd, skills), timestamp: Date.now() }],
    },
    { apiKey: auth.apiKey, headers: auth.headers, maxTokens: 1_000, temperature: 0 }
  );

  return selectionFromModelResponse(textFromAssistantMessage(message), skills);
}

async function createFirstRunSelection(cwd: string, skills: Skill[], ctx: ExtensionContext): Promise<SkillSelection> {
  try {
    const llmSelection = await createLlmSelection(cwd, skills, ctx);
    if (llmSelection) return llmSelection;
  } catch {}

  return createAutoSelection(cwd, skills);
}

function replacePromptSkillsSection(systemPrompt: string, replacement: string): string {
  const sectionIntro = "\n\nThe following skills provide specialized instructions for specific tasks.";
  const sectionStart = systemPrompt.lastIndexOf(sectionIntro);
  if (sectionStart === -1) return replacement ? systemPrompt + replacement : systemPrompt;

  const skillsEnd = systemPrompt.indexOf("</available_skills>", sectionStart);
  if (skillsEnd === -1) return replacement ? systemPrompt + replacement : systemPrompt;

  const sectionEnd = skillsEnd + "</available_skills>".length;
  return systemPrompt.slice(0, sectionStart) + replacement + systemPrompt.slice(sectionEnd);
}

function renderSkillsPrompt(skills: Skill[]): string {
  if (skills.length === 0) return "";

  const skillBlocks = skills
    .map(
      (skill) => `  <skill>
    <name>${escapeXml(skill.name)}</name>
    <description>${escapeXml(skill.description)}</description>
    <location>${escapeXml(skill.location)}</location>
    <source>${skill.source}</source>
  </skill>`
    )
    .join("\n");

  return `
## Skills

The following project-selected skills are available. Use the read tool to load a skill's file when the task matches its description. When a skill file references a relative path, resolve it against that skill file's directory.

<available_skills>
${skillBlocks}
</available_skills>
`;
}

function renderSelectionEditor(skills: Skill[], selection: SkillSelection): string {
  const enabledLocations = new Set(selection.enabledSkillLocations);
  const lines = [
    "# Pi project skill selection",
    "# Keep [x] for skills that should appear in the agent system prompt.",
    "# Change [x] to [ ] to disable, or [ ] to [x] to enable.",
    "",
  ];

  for (const skill of skills) {
    const marker = enabledLocations.has(skill.location) ? "[x]" : "[ ]";
    const description = skill.description ? ` - ${skill.description}` : "";
    lines.push(`${marker} ${skill.location} # ${skill.name} (${skill.source})${description}`);
  }

  return lines.join("\n") + "\n";
}

function parseSelectionEditor(text: string, skills: Skill[]): SkillSelection {
  const validLocations = new Set(skills.map((skill) => skill.location));
  const enabledSkillLocations: string[] = [];

  for (const line of text.split("\n")) {
    const match = line.match(/^\s*\[x\]\s+([^#]+?)(?:\s+#.*)?$/i);
    if (!match) continue;

    const location = match[1].trim();
    if (validLocations.has(location)) enabledSkillLocations.push(location);
  }

  return {
    version: 1,
    updatedAt: new Date().toISOString(),
    autoGenerated: false,
    selectionMethod: "manual",
    enabledSkillLocations,
  };
}

function renderSkillList(skills: Skill[], selection: SkillSelection): string {
  const enabledLocations = new Set(selection.enabledSkillLocations);
  return skills
    .map((skill) => {
      const marker = enabledLocations.has(skill.location) ? "✓" : " ";
      return `${marker} ${skill.name} (${skill.source}) — ${skill.description || skill.location}`;
    })
    .join("\n");
}

function renderContextSkillsStatus(message: string): string {
  return `${ORANGE_ANSI}[Context-Skills]${RESET_ANSI}\n  ${message}`;
}

export default async function (pi: ExtensionAPI) {
  const cwd = process.cwd();
  const skills = discoverSkills(cwd);
  if (skills.length === 0) return;

  let selection = loadSelection(cwd) ?? createAutoSelection(cwd, skills);
  let firstRunSelection: Promise<void> | undefined;

  function shouldRunFirstSelection(): boolean {
    const savedSelection = loadSelection(cwd);
    return !savedSelection || (savedSelection.autoGenerated && savedSelection.selectionMethod !== "llm");
  }

  function ensureFirstRunSelection(ctx: ExtensionContext): Promise<void> {
    if (!shouldRunFirstSelection()) return Promise.resolve();
    if (firstRunSelection) return firstRunSelection;

    firstRunSelection = createFirstRunSelection(cwd, skills, ctx).then((nextSelection) => {
      selection = nextSelection;
      try {
        saveSelection(selectionPath(cwd), selection);
        ctx.ui.notify(renderContextSkillsStatus(`Selected project skills: ${selectedSkills(skills, selection).length}/${skills.length} enabled`), "info");
      } catch {}
    });

    return firstRunSelection;
  }

  pi.on("session_start", async (_event, ctx) => {
    try {
      await ensureFirstRunSelection(ctx);
    } catch {}
  });

  pi.on("before_agent_start", async (event, ctx) => {
    try {
      await ensureFirstRunSelection(ctx);
    } catch {}

    const enabledLocations = new Set(selection.enabledSkillLocations);
    const promptSkills = event.systemPromptOptions.skills;
    if (promptSkills) {
      const filteredPromptSkills = promptSkills.filter((skill) => enabledLocations.has(skill.filePath));
      return {
        systemPrompt: replacePromptSkillsSection(event.systemPrompt, formatSkillsForPrompt(filteredPromptSkills)),
      };
    }

    const promptAddition = renderSkillsPrompt(selectedSkills(skills, selection));
    return { systemPrompt: replacePromptSkillsSection(event.systemPrompt, promptAddition) };
  });

  pi.registerCommand("skills", {
    description: "List, edit, or reset project-selected skills",
    handler: async (args, ctx) => {
      const action = (args ?? "").trim().toLowerCase() || "edit";
      const path = selectionPath(cwd);

      if (action === "list") {
        ctx.ui.notify(renderSkillList(skills, selection) || "No skills discovered", "info");
        return;
      }

      if (action === "reset") {
        selection = await createFirstRunSelection(cwd, skills, ctx);
        saveSelection(path, selection);
        ctx.ui.notify(renderContextSkillsStatus(`Reset project skill selection: ${selectedSkills(skills, selection).length}/${skills.length} enabled`), "info");
        return;
      }

      if (action !== "edit") {
        ctx.ui.notify("Usage: /skills [edit|list|reset]", "warning");
        return;
      }

      const edited = await ctx.ui.editor("Edit project skills", renderSelectionEditor(skills, selection));
      if (edited === undefined) return;

      selection = parseSelectionEditor(edited, skills);
      saveSelection(path, selection);
      ctx.ui.notify(renderContextSkillsStatus(`Saved project skill selection: ${selectedSkills(skills, selection).length}/${skills.length} enabled`), "info");
    },
  });
}
